language: php

dist: trusty
php:
  - "7.4"
  - "7.3"
  - "7.2"
  - "7.1"
  - "7.0"
  - "5.6"

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --verbose --coverage-clover coverage.clover --coverage-text

after_success:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
